spring:
  datasource:
    url: ${JDBC_CONNECTION_DB_URL}
    username: ${JDBC_CONNECTION_DB_NAME}
    password: ${JDBC_CONNECTION_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    port: 587
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
#      expiration: 3600000 # 30000 = 30s (1000 millisecond = 1s)
      expiration: 360000000
      refresh-token:
        expiration: 604800000
  stock:
    id: ${STOCK_ID}
  frontend-url: http://localhost:3000
  backend-url: http://192.168.1.34:8080
  logo-url: https://res.cloudinary.com/dnahocnhk/image/upload/f_png,b_white/v1762831622/fwf-logo_veozws.webp
  deploy-frontend-url: ${BACKEND_URL}
  deploy-backend-url: ${FRONTEND_URL}
gg:
  jte:
    developmentMode: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
#  pattern:
#    level: %5p

server:
  servlet:
    session:
      timeout: 20m
#  tomcat:
#    max-connections: 150
#    max-threads: 75
#    accept-count: 50
#    connection-timeout: 5000
#    keep-alive-timeout: 5s
#  address: 127.0.0.1
#  port: 8080

