#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/temp_crm?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
#    username: root
#    password: fwf@password123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    database: mysql
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#application:
#  security:
#    jwt:
#      secret-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqRz4bsW8hz8ZjRAZWTN4wZz9Q
#      expiration: 3600000 # 30000 = 30s (1000 millisecond = 1s)
#      #      expiration: 6048000000000
#      refresh-token:
#        expiration: 604800000
#  deploy:
#    path: http://103.157.220.55:8080
#    vercel_path: fbnetworkdev.vercel.app
#
#gg:
#  jte:
#    developmentMode: true
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: INFO
#    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
#server:
#  servlet:
#    session:
#      timeout: 30m